theme: jekyll-theme-cayman
title: My Progress Journal
description: IE38A Summer 2020 - Boğaziçi University

## Assignments

[Assignment 1](https://elifbayindir.github.io/boun01-elifbayindir/hw1.html)
